; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nano_esp32

[env:nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
upload_protocol = esptool
upload_speed = 460800
monitor_speed = 115200
build_src_filter = +<nanoesp.cpp>
build_flags = 
	-D BOARD_USES_HW_GPIO_NUMBERS
lib_deps = bblanchon/ArduinoJson@^7.0.4

[env:nano_esp32_dfu]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
upload_protocol = dfu
monitor_speed = 115200
build_src_filter = +<nanoesp.cpp>
build_flags = 
	-D BOARD_USES_HW_GPIO_NUMBERS
lib_deps = bblanchon/ArduinoJson@^7.0.4

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM5
board_build.flash_size = 4MB
board_build.partitions = min_spiffs.csv
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter = +<ESP32_GPS_MPU6050_Dashboard.cpp>
lib_deps = 
	adafruit/Adafruit MPU6050 @ ^2.2.6
	adafruit/Adafruit Unified Sensor @ ^1.1.14
	mikalhart/TinyGPSPlus @ ^1.0.3

[env:esp32dev_ota]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = esp32-telemetry.local
upload_flags = 
	--auth=admin
build_src_filter = +<ESP32_GPS_MPU6050_Dashboard.cpp>
lib_deps = 
	adafruit/Adafruit MPU6050 @ ^2.2.6
	adafruit/Adafruit Unified Sensor @ ^1.1.14
	mikalhart/TinyGPSPlus @ ^1.0.3

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	adafruit/DHT sensor library @ ^1.4.6
	adafruit/Adafruit Unified Sensor @ ^1.1.14
